language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2

before_install:
  - source .travis/set_release_version.sh

before_deploy:
  - .travis/setup_gpg.sh

deploy:
  provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file:
      - epsilon-runtime-utils/target/epsilon-runtime-utils-$project_version.jar
      - epsilon-runtime-executable/target/epsilon-runtime-executable-$project_version.jar
    skip_cleanup: true
    on:
      repo: BlackBeltTechnology/epsilon-runtime
    name: $PROJECT_VERSION

install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true 

script: 
  mvn clean deploy --settings .maven.xml -DskipTests=true -P release
